# Generated by Django 5.2.4 on 2026-03-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('extract', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('wikipedia_url', models.URLField(blank=True, max_length=500)),
                ('wikipedia_slug', models.CharField(blank=True, max_length=200)),
                ('epstein_mentions', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'celebrities',
                'ordering': ['-epstein_mentions'],
            },
        ),
    ]
