# Generated by Django 5.2.4 on 2026-03-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrity',
            name='description',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
